### ISSUE TITLE
which script consists of kernel granger casuality function?

### ISSUE THREAD

**Issue by manvirvirk** [danielemarinazzo/KernelGrangerCausality#2]

**Comment by danielemarinazzo** [comment]
causality.m is the main function, it calls other ones.

**Comment by manvirvirk** [comment]
Thanks for the information, i could use it now. I have one more query how to apply granger causality for non-stationary signals as it is meant that it can be applied only for stationary signals.

**Comment by danielemarinazzo** [comment]
If your time series do not satisfy the stationarity criterion of your choice, then you should use a sliding window (if you have enough samples per window and/or multiple trials), or use another time varying approach.

**Comment by manvirvirk** [comment]
@danielemarinazzo  i have non stationary brain signal with several trials. I have filtered it and windowed it into 2s segment. After this i got matrix of 500 by 35 to which i applied granger to select columns . Is this the way you you are saying?

**Comment by danielemarinazzo** [comment]
and where are you using the trials? what is 500 and what is 35?

**Comment by manvirvirk** [comment]
@danielemarinazzo 500 are trials and 35 are number of channels of brain signals

**Comment by danielemarinazzo** [comment]
This indeed allows you to perform a time point by time point analysis, but
not Granger causality since all data refers to the same time point. The
minimal window should be equal to the order of your auto regressive model
plus one.

**Comment by manvirvirk** [comment]
@danielemarinazzo  does this repo, causality.m find the granger causality or not?

**Comment by danielemarinazzo** [comment]
the repo or the function? The function causality.m computes Granger
causality indeed.

**Comment by manvirvirk** [comment]
ok thank you for the help @danielemarinazzo  (y)
