### ISSUE TITLE
Hello, I would like to inquire about a question regarding a formula in a paper. 

### ISSUE THREAD

**Issue by symbold** [danielemarinazzo/KernelGrangerCausality#3]
Hello, I would like to inquire about a question regarding a formula in a paper. Why is the 2-norm of \( x - \tilde{x} \) equal to \( 1 - \tilde{x}^T \tilde{x} \)?
![微信截图_20240518113717](https://github.com/danielemarinazzo/KernelGrangerCausality/assets/98453154/63462c34-8bbe-47e2-8392-b43931470811)

**Comment by danielemarinazzo** [comment]
The expansion gives  xTx - 2 xTx̃' + x̃'Tx̃'. But xTx̃' = x̃'Tx̃' given that x-x̃' is orthogonal to x̃'. So we're left with xTx-x'Tx̃'. xTx is equal to 1.

**Comment by symbold** [comment]
I got it, thank you very much for your help.
